Added how to sponsor page
wearhackskw/wearhackskw.github.io pull request #12
Opened 2016-11-15 01:08 UTC by rlee05

https://www.pivotaltracker.com/story/show/133400307

2016-11-15 01:25 UTC, AdrianMachado requested changes
fix dis

2016-11-15 01:25 UTC, AdrianMachado commented on how_to_sponsor.html
> +                <p style="text-align: center; font-size: 1.5em;">This amazing learning opportunity would not be possible without the fantastic support of our sponsors. We strive to maintain long-term
> community and if 

Insert comma after community

2016-11-15 01:25 UTC, AdrianMachado commented on how_to_sponsor.html
> +</html>
Add newline at the end of file

2016-11-15 01:25 UTC, AdrianMachado commented on how_to_sponsor.html
> +                <p style="text-align: center; font-size: 1.5em;">Contact the KW chapter at <a href="mailto:waterloo@wearhacks.com">waterloo@wearhacks.com</a> to find our how to help and how we can he
> our how to help and

*out
also put a comma after the help

2016-11-15 01:28 UTC, albertghionea commented
Will require slight changes to the css/js file paths post-refactor. example: creative.css will no longer exist (merged into styles.css)

Nice work getting it done so quickly

2016-11-15 01:34 UTC, rlee05 commented
@albertghionea so I'll just keep creative.css in for now?

2016-11-15 01:37 UTC, AdrianMachado commented
@rlee05 Wait till Albert's PR is approved, pull master, then fix it to work with styles
Edit: @rlee05 No thumbs pls, Hooray reacts only

2016-11-16 20:08 UTC, timmui commented
@rlee05 can you actually move the CSS you need into a seperate file so it will be easier to move into @albertghionea's changes later?

2016-11-16 20:19 UTC, timmui requested changes

2016-11-16 20:19 UTC, timmui commented on how_to_sponsor.html
> +                        <a class="page-scroll" href="#page-top">Attend</a>
Shouldn't this link back to the index page instead of anchors on this page?

2016-11-16 20:19 UTC, timmui commented on how_to_sponsor.html
> +</html>
There is a new line already, theres a symbol if theres no new line in github

2016-11-16 20:19 UTC, timmui commented on how_to_sponsor.html
> +<!DOCTYPE html>
Should probably find a place in `index.html` to link back to this page and include that as part of this PR or this page would never bee seen

2016-11-17 01:10 UTC, rlee05 commented
@timmui like just make a css that includes the things I need?

2016-11-17 01:22 UTC, albertghionea commented
Things that will change post-refactor:

<link rel="stylesheet" href="stylesheets/_base.css" type="text/css" /> will be removed; _base.css will no longer exist.

<link rel="stylesheet" href="stylesheets/css/creative.css" type="text/css" /> will be removed; creative.css will no longer exist; it is merged into styles.css.

<link rel="stylesheet" href="stylesheets/css/styles.css" type="text/css" /> will become <link rel="stylesheet" href="stylesheets/styles.css" type="text/css" /> ; the css folder is gone since it was redundant.

Bootstrap and fonts under bower components are being kept so those are ok.

@rlee05 if you created css classes/ids specifically for this page, a separate css file would make sense. If not, no need

2016-11-22 05:22 UTC, timmui commented
@albertghionea When you merge in #11 , fix and merge this in too

2016-12-20 19:13 UTC, merged